### ISSUE TITLE
GHC 8.0.1-rc4 build failure

### ISSUE THREAD

**Issue by deepfire** [diagrams/diagrams-lib#272] opened 2016-05-02 15:02 UTC
```
[41 of 72] Compiling Diagrams.Align   ( src/Diagrams/Align.hs, dist/build/Diagrams/Align.o )

src/Diagrams/Align.hs:63:3: error:
    • Constraint ‘HasOrigin a’ in the type of ‘alignBy'’
        constrains only the class type variables
      Use ConstrainedClassMethods to allow it
    • When checking the class method:
        alignBy' :: forall a.
                    Alignable a =>
                    forall (v :: * -> *) n.
                    (InSpace v n a, Fractional n, HasOrigin a) =>
                    (v n -> a -> Point v n) -> v n -> n -> a -> a
      In the class declaration for ‘Alignable’

src/Diagrams/Align.hs:69:3: error:
    • Constraint ‘HasOrigin a’ in the type of ‘alignBy’
        constrains only the class type variables
      Use ConstrainedClassMethods to allow it
    • When checking the class method:
        alignBy :: forall a.
                   Alignable a =>
                   forall (v :: * -> *) n.
                   (InSpace v n a, Fractional n, HasOrigin a) =>
                   v n -> n -> a -> a
      In the class declaration for ‘Alignable’
note: keeping build directory ‘/tmp/nix-build-diagrams-lib-1.3.1.1.drv-2’
builder for ‘/nix/store/qi6qyjw3n8l6iidz6znhj6lljydbsjcr-diagrams-lib-1.3.1.1.drv’ failed with exit code 1
error: build of ‘/nix/store/qi6qyjw3n8l6iidz6znhj6lljydbsjcr-diagrams-lib-1.3.1.1.drv’ failed
```

**Comment by deepfire** [comment] 2016-05-02 15:03
Full log:
```
hese derivations will be built:
  /nix/store/qi6qyjw3n8l6iidz6znhj6lljydbsjcr-diagrams-lib-1.3.1.1.drv
building path(s) ‘/nix/store/257rjgn1jkdmxzn8gwnr1sziasxfjql8-diagrams-lib-1.3.1.1’
setupCompilerEnvironmentPhase
Build with /nix/store/57zrq025ih51wf09zi7i03jnkr16957h-ghc-8.0.0.20160421.
unpacking sources
unpacking source archive /nix/store/rjn33nlhbh6xy7l1mb9zff3rxlssfn68-diagrams-lib-1.3.1.1.tar.g
z
source root is diagrams-lib-1.3.1.1
setting SOURCE_DATE_EPOCH to timestamp 1455905461 of file diagrams-lib-1.3.1.1/CHANGELOG.md
patching sources
Run jailbreak-cabal to lift version restrictions on build inputs.
compileBuildDriverPhase
setupCompileFlags: -package-db=/tmp/nix-build-diagrams-lib-1.3.1.1.drv-0/package.conf.d -j8 -th
readed
[1 of 1] Compiling Main             ( Setup.hs, /tmp/nix-build-diagrams-lib-1.3.1.1.drv-0/Main.
o )
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/257rjgn1jkdmxzn8gwnr1sziasxfjql8-diagrams-lib-1.3
.1.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --with-gcc=gcc --package-db=/tmp/nix-bui
ld-diagrams-lib-1.3.1.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-rpath=/nix/store/257rjgn1j
kdmxzn8gwnr1sziasxfjql8-diagrams-lib-1.3.1.1/lib/ghc-8.0.0.20160421/diagrams-lib-1.3.1.1 --enab
le-split-objs --disable-library-profiling --disable-profiling --enable-shared --enable-library-
vanilla --enable-executable-dynamic --enable-tests
Configuring diagrams-lib-1.3.1.1...
Dependency JuicyPixels -any: using JuicyPixels-3.2.7
Dependency active -any: using active-0.2.0.8
Dependency adjunctions -any: using adjunctions-4.3
Dependency array -any: using array-0.5.1.1
Dependency base -any: using base-4.9.0.0
Dependency colour -any: using colour-2.3.3
Dependency containers -any: using containers-0.5.7.1
Dependency data-default-class -any: using data-default-class-0.0.1
Dependency diagrams-core -any: using diagrams-core-1.3.0.6
Dependency diagrams-lib -any: using diagrams-lib-1.3.1.1
Dependency diagrams-solve -any: using diagrams-solve-0.1.0.1
Dependency directory -any: using directory-1.2.6.2
Dependency distributive -any: using distributive-0.5.0.2
Dependency dual-tree -any: using dual-tree-0.2.0.9
Dependency exceptions -any: using exceptions-0.8.2.1
Dependency filepath -any: using filepath-1.4.1.0
Dependency fingertree -any: using fingertree-0.1.1.0
Dependency fsnotify -any: using fsnotify-0.2.1
Dependency hashable -any: using hashable-1.2.4.0
Dependency intervals -any: using intervals-0.7.2
Dependency lens -any: using lens-4.14
Dependency linear -any: using linear-1.20.5
Dependency monoid-extras -any: using monoid-extras-0.4.0.4
Dependency mtl -any: using mtl-2.2.1
Dependency optparse-applicative -any: using optparse-applicative-0.12.1.0
Dependency process -any: using process-1.4.2.0
Dependency semigroups -any: using semigroups-0.18.1
Dependency tagged -any: using tagged-0.8.3
Dependency tasty -any: using tasty-0.11.0.2
Dependency tasty-hunit -any: using tasty-hunit-0.9.2
Dependency text -any: using text-1.2.2.1
Dependency transformers -any: using transformers-0.5.2.0
Dependency unordered-containers -any: using unordered-containers-0.2.7.0
Using Cabal-1.24.1.0 compiled by ghc-8.0
Using compiler: ghc-8.0.0.20160421
Using install prefix:
/nix/store/257rjgn1jkdmxzn8gwnr1sziasxfjql8-diagrams-lib-1.3.1.1
Binaries installed in:
/nix/store/257rjgn1jkdmxzn8gwnr1sziasxfjql8-diagrams-lib-1.3.1.1/bin
Libraries installed in:
/nix/store/257rjgn1jkdmxzn8gwnr1sziasxfjql8-diagrams-lib-1.3.1.1/lib/ghc-8.0.0.20160421/diagram
s-lib-1.3.1.1
Private binaries installed in:
/nix/store/257rjgn1jkdmxzn8gwnr1sziasxfjql8-diagrams-lib-1.3.1.1/libexec
Data files installed in:
/nix/store/257rjgn1jkdmxzn8gwnr1sziasxfjql8-diagrams-lib-1.3.1.1/share/x86_64-linux-ghc-8.0.0.2
0160421/diagrams-lib-1.3.1.1
Documentation installed in:
/nix/store/257rjgn1jkdmxzn8gwnr1sziasxfjql8-diagrams-lib-1.3.1.1/share/doc/x86_64-linux-ghc-8.0
.0.20160421/diagrams-lib-1.3.1.1
Configuration files installed in:
/nix/store/257rjgn1jkdmxzn8gwnr1sziasxfjql8-diagrams-lib-1.3.1.1/etc
No alex found
Using ar found on system at:
/nix/store/s0kpgl8a101lkymj599f5a04s4wflf5s-binutils-2.26-dev/bin/ar
No c2hs found
No cpphs found
Using gcc version 5.3.0 given by user at:
/nix/store/ix03iknfgyrx7421fppjdczd9r4sw7pz-gcc-wrapper-5.3.0/bin/gcc
Using ghc version 8.0.0.20160421 found on system at:
/nix/store/57zrq025ih51wf09zi7i03jnkr16957h-ghc-8.0.0.20160421/bin/ghc
Using ghc-pkg version 8.0.0.20160421 found on system at:
/nix/store/57zrq025ih51wf09zi7i03jnkr16957h-ghc-8.0.0.20160421/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.17.0 found on system at:
/nix/store/57zrq025ih51wf09zi7i03jnkr16957h-ghc-8.0.0.20160421/bin/haddock
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at:
/nix/store/57zrq025ih51wf09zi7i03jnkr16957h-ghc-8.0.0.20160421/bin/hpc
Using hsc2hs version 0.68 found on system at:
/nix/store/57zrq025ih51wf09zi7i03jnkr16957h-ghc-8.0.0.20160421/bin/hsc2hs
Using hscolour version 1.24 found on system at:
/nix/store/1dczsrvfp57p6rz1awyhq2qmdk2qjp17-hscolour-1.24/bin/HsColour
No jhc found
Using ld found on system at:
/nix/store/ix03iknfgyrx7421fppjdczd9r4sw7pz-gcc-wrapper-5.3.0/bin/ld
No lhc found
No lhc-pkg found
No pkg-config found
Using strip version 2.26 found on system at:
/nix/store/s0kpgl8a101lkymj599f5a04s4wflf5s-binutils-2.26-dev/bin/strip
Using tar found on system at:
/nix/store/acikdr9h8d0jmrjxfyyh6mnh8dznqv8a-gnutar-1.28/bin/tar
No uhc found
building
Building diagrams-lib-1.3.1.1...
Preprocessing library diagrams-lib-1.3.1.1...
[ 1 of 72] Compiling Diagrams.ThreeD.Attributes ( src/Diagrams/ThreeD/Attributes.hs, dist/build
/Diagrams/ThreeD/Attributes.o )
[ 2 of 72] Compiling Diagrams.CubicSpline.Internal ( src/Diagrams/CubicSpline/Internal.hs, dist
/build/Diagrams/CubicSpline/Internal.o )
[ 3 of 72] Compiling Diagrams.Attributes.Compile ( src/Diagrams/Attributes/Compile.hs, dist/bui
ld/Diagrams/Attributes/Compile.o )
[ 4 of 72] Compiling Diagrams.Util    ( src/Diagrams/Util.hs, dist/build/Diagrams/Util.o )
[ 5 of 72] Compiling Diagrams.Points  ( src/Diagrams/Points.hs, dist/build/Diagrams/Points.o )
[ 6 of 72] Compiling Diagrams.Angle   ( src/Diagrams/Angle.hs, dist/build/Diagrams/Angle.o )
[ 7 of 72] Compiling Diagrams.Direction ( src/Diagrams/Direction.hs, dist/build/Diagrams/Direct
ion.o )
[ 8 of 72] Compiling Diagrams.Coordinates ( src/Diagrams/Coordinates.hs, dist/build/Diagrams/Co
ordinates.o )
[ 9 of 72] Compiling Diagrams.TwoD.Types ( src/Diagrams/TwoD/Types.hs, dist/build/Diagrams/TwoD
/Types.o )
[10 of 72] Compiling Diagrams.TwoD.Vector ( src/Diagrams/TwoD/Vector.hs, dist/build/Diagrams/Tw
oD/Vector.o )
[11 of 72] Compiling Diagrams.TwoD.Points ( src/Diagrams/TwoD/Points.hs, dist/build/Diagrams/Tw
oD/Points.o )
[12 of 72] Compiling Diagrams.ThreeD.Types ( src/Diagrams/ThreeD/Types.hs, dist/build/Diagrams/
ThreeD/Types.o )
[13 of 72] Compiling Diagrams.ThreeD.Light ( src/Diagrams/ThreeD/Light.hs, dist/build/Diagrams/
ThreeD/Light.o )

src/Diagrams/ThreeD/Light.hs:47:10: warning: [-Wredundant-constraints]
    • Redundant constraint: Fractional n
    • In the instance declaration for ‘Transformable (ParallelLight n)’
[14 of 72] Compiling Diagrams.ThreeD.Vector ( src/Diagrams/ThreeD/Vector.hs, dist/build/Diagram
s/ThreeD/Vector.o )
[15 of 72] Compiling Diagrams.ThreeD.Shapes ( src/Diagrams/ThreeD/Shapes.hs, dist/build/Diagram
s/ThreeD/Shapes.o )
[16 of 72] Compiling Diagrams.ThreeD.Camera ( src/Diagrams/ThreeD/Camera.hs, dist/build/Diagram
s/ThreeD/Camera.o )

src/Diagrams/ThreeD/Camera.hs:144:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Fractional n
    • In the type signature for:
           camForward :: Fractional n => Camera l n -> Direction V3 n

src/Diagrams/ThreeD/Camera.hs:147:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Fractional n
    • In the type signature for:
           camUp :: Fractional n => Camera l n -> Direction V3 n
[17 of 72] Compiling Diagrams.Transform.Matrix ( src/Diagrams/Transform/Matrix.hs, dist/build/D
iagrams/Transform/Matrix.o )
[18 of 72] Compiling Diagrams.Query   ( src/Diagrams/Query.hs, dist/build/Diagrams/Query.o )
[19 of 72] Compiling Diagrams.Names   ( src/Diagrams/Names.hs, dist/build/Diagrams/Names.o )
[20 of 72] Compiling Diagrams.Transform ( src/Diagrams/Transform.hs, dist/build/Diagrams/Transf
orm.o )

src/Diagrams/Transform.hs:46:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Functor v
    • In the type signature for:
           conjugate :: (Additive v, Num n, Functor v) =>
                        Transformation v n -> Transformation v n -> Transformation v n
[21 of 72] Compiling Diagrams.TwoD.Transform ( src/Diagrams/TwoD/Transform.hs, dist/build/Diagr
ams/TwoD/Transform.o )
[22 of 72] Compiling Diagrams.ThreeD.Transform ( src/Diagrams/ThreeD/Transform.hs, dist/build/D
iagrams/ThreeD/Transform.o )
[23 of 72] Compiling Diagrams.Transform.ScaleInv ( src/Diagrams/Transform/ScaleInv.hs, dist/bui
ld/Diagrams/Transform/ScaleInv.o )

src/Diagrams/Transform/ScaleInv.hs:186:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Transformable t
    • In the type signature for:
           scaleInvPrim :: (V t ~ V2, N t ~ n, RealFloat n, Transformable t,
                            Typeable t, Renderable t b, Monoid m) =>
                           t -> V2 n -> QDiagram b (V t) (N t) m
[24 of 72] Compiling Diagrams.Parametric ( src/Diagrams/Parametric.hs, dist/build/Diagrams/Para
metric.o )
[25 of 72] Compiling Diagrams.Parametric.Adjust ( src/Diagrams/Parametric/Adjust.hs, dist/build
/Diagrams/Parametric/Adjust.o )

src/Diagrams/Parametric/Adjust.hs:84:1: warning: [-Wredundant-constraints]
    • Redundant constraints: (V t ~ v, DomainBounds t)
    • In the type signature for:
           adjust :: (V t ~ v, N t ~ n, DomainBounds t, Sectionable t,
                      HasArcLength t, Fractional n) =>
                     t -> AdjustOpts n -> t
[26 of 72] Compiling Diagrams.TwoD.Segment.Bernstein ( src/Diagrams/TwoD/Segment/Bernstein.hs,
dist/build/Diagrams/TwoD/Segment/Bernstein.o )
[27 of 72] Compiling Diagrams.Located ( src/Diagrams/Located.hs, dist/build/Diagrams/Located.o
)
[28 of 72] Compiling Diagrams.Segment ( src/Diagrams/Segment.hs, dist/build/Diagrams/Segment.o
)
[29 of 72] Compiling Diagrams.Tangent ( src/Diagrams/Tangent.hs, dist/build/Diagrams/Tangent.o
)
[30 of 72] Compiling Diagrams.Trail   ( src/Diagrams/Trail.hs, dist/build/Diagrams/Trail.o )

src/Diagrams/Trail.hs:143:10: warning: [-Wredundant-constraints]
    • Redundant constraints: (Metric (V a), OrderedField (N a))
    • In the instance declaration for ‘Transformable (FingerTree m a)’

src/Diagrams/Trail.hs:310:1: warning: [-Wredundant-constraints]
    • Redundant constraints: (Metric v, OrderedField n)
    • In the type signature for:
           trailMeasure :: (Metric v, OrderedField n, SegMeasure v n :>: m,
                            FT.Measured (SegMeasure v n) t) =>
                           a -> (m -> a) -> t -> a

src/Diagrams/Trail.hs:637:10: warning: [-Wredundant-constraints]
    • Redundant constraint: Real n
    • In the instance declaration for
        ‘EndValues (GetSegment (Trail' Line v n))’

src/Diagrams/Trail.hs:1077:1: warning: [-Wredundant-constraints]
    • Redundant constraints: (Metric v, OrderedField n)
    • In the type signature for:
           lineOffsets :: (Metric v, OrderedField n) =>
                          Trail' Line v n -> [v n]
[31 of 72] Compiling Diagrams.TwoD.Curvature ( src/Diagrams/TwoD/Curvature.hs, dist/build/Diagr
ams/TwoD/Curvature.o )
[32 of 72] Compiling Diagrams.TrailLike ( src/Diagrams/TrailLike.hs, dist/build/Diagrams/TrailL
ike.o )

src/Diagrams/TrailLike.hs:200:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Additive v
    • In the type signature for:
           explodeTrail :: (V t ~ v, N t ~ n, Additive v, TrailLike t) =>
                           Located (Trail v n) -> [t]
[33 of 72] Compiling Diagrams.Animation.Active ( src/Diagrams/Animation/Active.hs, dist/build/D
iagrams/Animation/Active.o )
[34 of 72] Compiling Diagrams.CubicSpline ( src/Diagrams/CubicSpline.hs, dist/build/Diagrams/Cu
bicSpline.o )
[35 of 72] Compiling Diagrams.TwoD.Arc ( src/Diagrams/TwoD/Arc.hs, dist/build/Diagrams/TwoD/Arc
.o )
[36 of 72] Compiling Diagrams.TwoD.Ellipse ( src/Diagrams/TwoD/Ellipse.hs, dist/build/Diagrams/
TwoD/Ellipse.o )

src/Diagrams/TwoD/Ellipse.hs:38:1: warning: [-Wredundant-constraints]
    • Redundant constraint: RealFloat n
    • In the type signature for:
           unitCircle :: (TrailLike t, V t ~ V2, N t ~ n, RealFloat n) => t
[37 of 72] Compiling Diagrams.TwoD.Segment ( src/Diagrams/TwoD/Segment.hs, dist/build/Diagrams/TwoD/Segment.o )
[38 of 72] Compiling Diagrams.Combinators ( src/Diagrams/Combinators.hs, dist/build/Diagrams/Combinators.o )

src/Diagrams/Combinators.hs:76:1: warning: [-Wredundant-constraints]
    • Redundant constraints: (Metric v, OrderedField n)
    • In the type signature for:
           withEnvelope :: (InSpace v n a, Metric v, OrderedField n,
                            Monoid' m, Enveloped a) =>
                           a -> QDiagram b v n m -> QDiagram b v n m

src/Diagrams/Combinators.hs:120:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Monoid' m
    • In the type signature for:
           strut :: (Metric v, OrderedField n, Monoid' m) =>
                    v n -> QDiagram b v n m
[39 of 72] Compiling Diagrams.Envelope ( src/Diagrams/Envelope.hs, dist/build/Diagrams/Envelope.o )
[40 of 72] Compiling Diagrams.Trace   ( src/Diagrams/Trace.hs, dist/build/Diagrams/Trace.o )
[41 of 72] Compiling Diagrams.Align   ( src/Diagrams/Align.hs, dist/build/Diagrams/Align.o )

src/Diagrams/Align.hs:63:3: error:
    • Constraint ‘HasOrigin a’ in the type of ‘alignBy'’
        constrains only the class type variables
      Use ConstrainedClassMethods to allow it
    • When checking the class method:
        alignBy' :: forall a.
                    Alignable a =>
                    forall (v :: * -> *) n.
                    (InSpace v n a, Fractional n, HasOrigin a) =>
                    (v n -> a -> Point v n) -> v n -> n -> a -> a
      In the class declaration for ‘Alignable’

src/Diagrams/Align.hs:69:3: error:
    • Constraint ‘HasOrigin a’ in the type of ‘alignBy’
        constrains only the class type variables
      Use ConstrainedClassMethods to allow it
    • When checking the class method:
        alignBy :: forall a.
                   Alignable a =>
                   forall (v :: * -> *) n.
                   (InSpace v n a, Fractional n, HasOrigin a) =>
                   v n -> n -> a -> a
      In the class declaration for ‘Alignable’
note: keeping build directory ‘/tmp/nix-build-diagrams-lib-1.3.1.1.drv-2’
builder for ‘/nix/store/qi6qyjw3n8l6iidz6znhj6lljydbsjcr-diagrams-lib-1.3.1.1.drv’ failed with exit code 1
error: build of ‘/nix/store/qi6qyjw3n8l6iidz6znhj6lljydbsjcr-diagrams-lib-1.3.1.1.drv’ failed
```

**Comment by byorgey** [comment] 2016-05-02 15:09
Thanks for the report!  I should have time to look into this soon.

**Comment by bergey** [comment] 2016-05-02 20:37
Thanks for the report.  I thought I had already pushed a patch for this, but I see I didn't.  I think adding the language pragma is enough; I'll verify and push.

**Comment by byorgey** [comment] 2016-05-02 21:56
Should we also address the "redundant constraint" warnings?  Or are you saying those are addressed by the language pragma as well?

**Comment by bergey** [comment] 2016-05-03 00:53
I have not figured out the "redundant constraint" warnings.  Are the only redundant with GHC 8?

**Comment by byorgey** [comment] 2016-05-03 02:55
I was assuming so, but I am not actually sure, now that you ask.

**Comment by bergey** [comment] 2016-05-03 11:50
Apparently the warning is new with GHC-8.  I now think the constraints were always redundant.  We've been a little lazy about tossing in `Metric` and `Floating` constraints.

**Comment by bergey** [comment] 2016-05-03 13:03
There are a *lot* of redundant constraints.  WIP [here](https://github.com/diagrams/diagrams-lib/tree/redundant-constraints).  I expect to finish this evening.

**Comment by fakedrake** [comment] 2016-06-04 08:52
Is this the root cause of this issue?

```
$ cabal sandbox init
Writing a default package environment file to
/private/tmp/sandgrams/cabal.sandbox.config
Creating a new sandbox at /private/tmp/sandgrams/.cabal-sandbox
$ cabal install diagrams 
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: diagrams-1.3.0.1 (user goal)
trying: diagrams-1.3.0.1:-canvas
trying: diagrams-1.3.0.1:-rasterific
trying: diagrams-1.3.0.1:-ps
trying: diagrams-1.3.0.1:-postscript
trying: diagrams-1.3.0.1:+svg
trying: diagrams-svg-1.4.0.1 (dependency of diagrams-1.3.0.1:+svg)
trying: base-4.9.0.0/installed-4.9... (dependency of diagrams-svg-1.4.0.1)
trying: diagrams-1.3.0.1:-gtk
trying: diagrams-1.3.0.1:-cairo
next goal: diagrams-contrib (dependency of diagrams-1.3.0.1)
rejecting: diagrams-contrib-1.3.0.10, 1.3.0.9, 1.3.0.8, 1.3.0.7, 1.3.0.6,
1.3.0.5, 1.3.0.4, 1.3.0.3, 1.3.0.2, 1.3.0.1, 1.3.0 (conflict:
base==4.9.0.0/installed-4.9..., diagrams-contrib => base>=4.2 && <4.9)
rejecting: diagrams-contrib-1.1.2.6, 1.1.2.5, 1.1.2.4, 1.1.2.3, 1.1.2.2,
1.1.2.1, 1.1.2, 1.1.1.5, 1.1.1.4, 1.1.1.3, 1.1.1.2, 1.1.1.1, 1.1.1, 1.1.0.1,
1.1, 1.0.0.1, 1.0, 0.7, 0.6.1, 0.6.0.4, 0.6.0.3, 0.6.0.2, 0.6.0.1, 0.6,
0.1.1.1, 0.1.1.0, 0.1.0.0 (conflict: diagrams => diagrams-contrib>=1.3 &&
<1.4)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by byorgey** [comment] 2016-06-04 10:09
@fakedrake not really, there's not any particular root cause, just a lot of little things that need to be updated.  We're working on it and should have an update released soon.

**Comment by byorgey** [comment] 2016-06-08 17:34
The latest release of `diagrams-lib` now compiles successfully with GHC 8.0.1.

**Closed by byorgey** 2016-06-08 17:34 UTC
