### ISSUE TITLE
Test suite compilation failure

### ISSUE THREAD

**Issue by snoyberg** [diagrams/diagrams-lib#286] opened 2016-11-07 05:03 UTC
```
[6 of 7] Compiling Diagrams.Test.Angle ( test/Diagrams/Test/Angle.hs, dist/build/tests/tests-tmp/Diagrams/Test/Angle.o )
[7 of 7] Compiling Main             ( test/Test.hs, dist/build/tests/tests-tmp/Main.o )

test/Test.hs:9:1: error:
    Failed to load interface for ‘Diagrams.Test.Trail’
    Perhaps you meant Diagrams.Trail (from diagrams-lib-1.4)
    Use -v to see a list of the files searched for.
```

**Comment by byorgey** [comment] 2016-11-07 12:07
Thanks for the report!  Should be fixed in `diagrams-lib-1.4.0.1` by 719db6b.  I know exactly what the problem was---`Diagrams.Test.Trail` was not listed in the `other-modules` section of the `.cabal` file---but strangely I couldn't reproduce the error, the test suite ran fine for me without the fix.  Oh well.

**Closed by byorgey** 2016-11-07 12:07 UTC
